### ISSUE TITLE
Test failure in bdbcontrib check.sh on OS X

### ISSUE THREAD

**Issue by raxraxraxraxrax** [probcomp/bdbcontrib#104]
Got this error when trying to make a new virtual environment with a new build:

=================================== FAILURES ===================================
__________________ test_analyze_and_analysis_status_and_reset __________________

    def test_analyze_and_analysis_status_and_reset():
        with prepare() as (dts, _df):
            resultdf = dts.analysis_status()
            assert 'iterations' == resultdf.index.name, repr(resultdf)
            assert 'count of models' == resultdf.columns[0], repr(resultdf)
>           assert 1 == len(resultdf), repr(resultdf)
E           AssertionError: Empty DataFrame
E             Columns: [count of models]
E             Index: []
E           assert 1 == 0
E            +  where 0 = len(Empty DataFrame\nColumns: [count of models]\nIndex: [])

tests/test_recipes.py:106: AssertionError
----------------------------- Captured stderr call -----------------------------
Process Process-1:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/rax/newbuildtry/bdbcontrib/tests/test_recipes.py", line 95, in <lambda>
    ensure_timeout(10, lambda: dts.analyze(models=10, iterations=20))
  File "/Users/rax/newbuildtry/bdbcontrib/build/lib/bdbcontrib/recipes.py", line 154, in analyze
    (models, self.generator_name))
  File "/Users/rax/newbuildtry/bdbcontrib/build/lib/bdbcontrib/recipes.py", line 123, in q
    res = self.bdb.execute(query_string, args)
  File "/Users/rax/newbuildtry/bayeslite_venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 215, in execute
    self.tracer, self._do_execute, string, bindings)
  File "/Users/rax/newbuildtry/bayeslite_venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 223, in _maybe_trace
    return meth(string, bindings)
  File "/Users/rax/newbuildtry/bayeslite_venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 264, in _do_execute
    cursor = bql.execute_phrase(self, phrase, bindings)
  File "/Users/rax/newbuildtry/bayeslite_venv/lib/python2.7/site-packages/bayeslite/bql.py", line 387, in execute_phrase
    if not core.bayesdb_has_generator_default(bdb, phrase.generator):
  File "/Users/rax/newbuildtry/bayeslite_venv/lib/python2.7/site-packages/bayeslite/core.py", line 178, in bayesdb_has_generator_default
    return 0 != cursor_value(bdb.sql_execute(sql, {'name': name}))
  File "/Users/rax/newbuildtry/bayeslite_venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 281, in sql_execute
    self.sql_tracer, self._do_sql_execute, string, bindings)
  File "/Users/rax/newbuildtry/bayeslite_venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 223, in _maybe_trace
    return meth(string, bindings)
  File "/Users/rax/newbuildtry/bayeslite_venv/lib/python2.7/site-packages/bayeslite/bayesdb.py", line 284, in _do_sql_execute
    return bql.BayesDBCursor(self, self.sqlite3.execute(string, bindings))
OperationalError: no such table: bayesdb_generator
===================== 1 failed, 43 passed in 92.02 seconds =====================
(bayeslite_venv)Raxs-MacBook-Pro:newbuildtry rax$

**Comment by gregory-marton** [comment]
I think I see what's going on. The installer installs the 0.1.3 versions, but this needs a newer bayeslite than that. I'll update the testing instructions.

**Comment by raxraxraxraxrax** [comment]
Looks fixed on a newer attempt. Are we okay to close here?

**Comment by gregory-marton** [comment]
Yep. Closing.
