### ISSUE TITLE
population's ipython detection is wrong

### ISSUE THREAD

**Issue by riastradh-probcomp** [probcomp/bdbcontrib#133]
`import seaborn` has the effect of importing `IPython` so that `'IPython' in sys.modules` is true, whether or not you are using ipython, but https://github.com/probcomp/bdbcontrib/blob/3edf900e1b8babc2cae256df70f632cb90423f7f/src/population.py#L111 seems to assume that `'IPython' in sys.modules` implies there is a user using ipython.

**Comment by gregory-marton** [comment]
Nice catch. Do you know if there is a supported way of asking whether one is using the relevant code from ipython? How did you discover this?

**Comment by riastradh-probcomp** [comment]
test_method_calls of test_population_method.py choked on a bug deep inside ipython.  The ipython bug isn't important, but here's the stack trace.  It took me a while to figure out what was importing ipython -- I discovered it by sprinkling asserts into bayeslite.  Maybe there's a faster way to get a stack trace for when a module is first imported.

    ______________________________ test_method_calls _______________________________
    Traceback (most recent call last):
      File "/home/riastradh/bayesdb/bdbcontrib/tests/test_population_method.py", line 130, in test_method_calls
	session_capture_name='test_population.py')
      File "/home/riastradh/bayesdb/bdbcontrib/build/lib.linux-x86_64-2.7/bdbcontrib/__init__.py", line 30, in quickstart
	return Population(*args, **kwargs)
      File "/home/riastradh/bayesdb/bdbcontrib/build/lib.linux-x86_64-2.7/bdbcontrib/population.py", line 124, in __init__
	self.initialize()
      File "/home/riastradh/bayesdb/bdbcontrib/build/lib.linux-x86_64-2.7/bdbcontrib/population.py", line 170, in initialize
	self.generators = self.query('''SELECT * FROM bayesdb_generator''')
      File "/home/riastradh/bayesdb/bdbcontrib/build/lib.linux-x86_64-2.7/bdbcontrib/population_method.py", line 362, in as_population_method
	result = fn(*dargs, **dkwargs)
      File "/home/riastradh/bayesdb/bdbcontrib/build/lib.linux-x86_64-2.7/bdbcontrib/bql_utils.py", line 168, in query
	logger.info("BQL [%s] %s", bql, bindings)
      File "/home/riastradh/bayesdb/bdbcontrib/build/lib.linux-x86_64-2.7/bdbcontrib/loggers.py", line 31, in info
	IPython.display.display_html(html, raw=True)
      File "/usr/lib/python2.7/dist-packages/IPython/core/display.py", line 156, in display_html
	_display_mimetype('text/html', objs, **kwargs)
      File "/usr/lib/python2.7/dist-packages/IPython/core/display.py", line 73, in _display_mimetype
	display(*objs, raw=raw, metadata=metadata, include=[mimetype])
      File "/usr/lib/python2.7/dist-packages/IPython/core/display.py", line 114, in display
	publish_display_data('display', obj, metadata)
      File "/usr/lib/python2.7/dist-packages/IPython/core/displaypub.py", line 158, in publish_display_data
	InteractiveShell.instance().display_pub.publish(
      File "/usr/lib/python2.7/dist-packages/IPython/config/configurable.py", line 349, in instance
	inst = cls(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 474, in __init__
	self.init_readline()
      File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 1843, in init_readline
	self.refill_readline_hist()
      File "/usr/lib/python2.7/dist-packages/IPython/core/interactiveshell.py", line 1852, in refill_readline_hist
	stdin_encoding = sys.stdin.encoding or "utf-8"
    AttributeError: DontReadFromInput instance has no attribute 'encoding'
