### ISSUE TITLE
"unknown encoding" when installing bdbcontrib

### ISSUE THREAD

**Issue by alxempirical** [probcomp/bdbcontrib#140]
```bash
bash-3.2$ cd /tmp/
bash-3.2$ git clone https://github.com/probcomp/bdbcontrib/
Cloning into 'bdbcontrib'...
remote: Counting objects: 6930, done.        
remote: Compressing objects: 100% (126/126), done.        
remote: Total 6930 (delta 72), reused 0 (delta 0), pack-reused 6803        
Receiving objects: 100% (6930/6930), 30.95 MiB | 4.79 MiB/s, done.
Resolving deltas: 100% (4353/4353), done.
Checking connectivity... done.
bash-3.2$ cd bdbcontrib/
bash-3.2$ python setup.py develop
running develop
running egg_info
creating bdbcontrib.egg-info
writing requirements to bdbcontrib.egg-info/requires.txt
writing bdbcontrib.egg-info/PKG-INFO
writing top-level names to bdbcontrib.egg-info/top_level.txt
writing dependency_links to bdbcontrib.egg-info/dependency_links.txt
writing manifest file 'bdbcontrib.egg-info/SOURCES.txt'
reading manifest file 'bdbcontrib.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'tests/test_utils.py'
writing manifest file 'bdbcontrib.egg-info/SOURCES.txt'
running build_ext
Creating /Users/alx/anaconda/lib/python2.7/site-packages/bdbcontrib.egg-link (link to .)
Removing bdbcontrib 0.1.7.post151 from easy-install.pth file
Adding bdbcontrib 0.1.7.post151 to easy-install.pth file
Traceback (most recent call last):
  File "setup.py", line 213, in <module>
    'test': cmd_pytest,
  File "/Users/alx/anaconda/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/alx/anaconda/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/alx/anaconda/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/alx/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/setuptools/command/develop.py", line 34, in run
  File "/Users/alx/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/setuptools/command/develop.py", line 133, in install_for_development
  File "/Users/alx/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/setuptools/command/easy_install.py", line 697, in process_distribution
    
  File "/Users/alx/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/setuptools/command/develop.py", line 167, in install_egg_scripts
LookupError: unknown encoding: 
bash-3.2$ 
```

**Comment by alxempirical** [comment]
It's failing on an attempt to open the file `bayesdb-demo`:

```
bash-3.2$ python -i setup.py develop
....
LookupError: unknown encoding: 
>>> import pdb
>>> pdb.pm()
> /Useurs/alx/anaconda/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/setuptools/command/develop.py(167)install_egg_scripts()
-> with io.open(script_path) as strm:
(Pdb) l
162  	
163  	        # ...and old-style
164  	        for script_name in self.distribution.scripts or []:
165  	            script_path = os.path.abspath(convert_path(script_name))
166  	            script_name = os.path.basename(script_path)
167  ->	            with io.open(script_path) as strm:
168  	                script_text = strm.read()
169  	            self.install_script(dist, script_name, script_text, script_path)
170  	
171  	    def install_wrapper_scripts(self, dist):
172  	        dist = VersionlessRequirement(dist)
(Pdb) script_path
'/private/tmp/bdbcontrib/scripts/bayesdb-demo'
(Pdb) f = io.open(script_path)
*** LookupError: unknown encoding: 
(Pdb) 
```

**Comment by gregory-marton** [comment]
Sorry, wrong bug number. I meant #138

**Comment by gregory-marton** [comment]
Thanks for looking into it, @alxempirical!

**Comment by alxempirical** [comment]
Closing this unless I hear different from the [anaconda people](https://github.com/ContinuumIO/anaconda-issues/issues/787)
